# Generated by Django 2.2 on 2019-06-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Shoes', 'Shoes')], default='Clothes', max_length=2),
        ),
    ]
