# Generated by Django 2.2 on 2019-06-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_addproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Shoes', 'Shoes')], default='Clothes', max_length=50),
        ),
    ]
